development:
  adapter: postgresql
  encoding: unicode
  database: testable_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: testable_test
  pool: 5
  username: postgres
  password: postgres